// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerrosPeligrososApi.Data;

#nullable disable

namespace PerrosPeligrososApi.Migrations
{
    [DbContext(typeof(PerrosPeligrososApiDbContext))]
    [Migration("20250903010510_PrimeraXDXD")]
    partial class PrimeraXDXD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerrosPeligrososApi.Models.ChipPerroPeligroso", b =>
                {
                    b.Property<int>("PerroPeligrosoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PerroPeligrosoId");

                    b.ToTable("ChipsPerroPeligroso");
                });

            modelBuilder.Entity("PerrosPeligrososApi.Models.PerroPeligroso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ClienteDni")
                        .HasColumnType("bigint");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistroApi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MascotaIdOriginal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PerrosPeligrosos");
                });

            modelBuilder.Entity("PerrosPeligrososApi.Models.ChipPerroPeligroso", b =>
                {
                    b.HasOne("PerrosPeligrososApi.Models.PerroPeligroso", "PerroPeligroso")
                        .WithOne("Chip")
                        .HasForeignKey("PerrosPeligrososApi.Models.ChipPerroPeligroso", "PerroPeligrosoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerroPeligroso");
                });

            modelBuilder.Entity("PerrosPeligrososApi.Models.PerroPeligroso", b =>
                {
                    b.Navigation("Chip");
                });
#pragma warning restore 612, 618
        }
    }
}
